name: lab_actions

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest

  - name: Install lcov
    run: sudo apt-get install -y lcov

  - name: Configurate
    run: |
        rm -rf ${{github.workspace}}/_build
        mrdir _build && cd _build
        cmake ..
        cmake --build .

  - name: Run tests
    run: build/my_test